name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ uat ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Confirm start'     
        required: false
        default: 'yes'
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://kloudrealty.com/
    steps:
      - uses: actions/checkout@v4
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "
          cd /root/erpnext
          docker compose exec -it backend rm -fr /home/frappe/frappe-bench/apps/erpnext
          docker compose exec -it rm -fr /home/frappe/frappe-bench/sites/apps.json
          docker compose exec -it backend bench get-app erpnext --resolve-deps --branch uat https://github.com/kloudbroker/ultraerp
          docker compose exec -it backend bench migrate
          docker compose exec -it backend bench clear-website-cache
          docker compose exec -it backend bench clear-cache
          docker compose exec -it backend bench version"
