name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ version-15 ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Confirm start'     
        required: false
        default: 'yes'
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://kloudrealty.com/
    steps:
      - uses: actions/checkout@v4
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "
          docker compose exec -it backend git -C /home/frappe/frappe-bench/apps/erpnext pull
          docker compose exec -it backend /home/frappe/frappe-bench/env/bin/python -m pip install --upgrade -e /home/frappe/frappe-bench/apps/erpnext
          docker compose exec -it backend bench build --app erpnext
          docker compose exec -it backend bench migrate
          docker compose exec -it backend bench clear-website-cache
          docker compose exec -it backend bench clear-cache"
